#[derive(Debug, Clone, PartialEq, Eq, sqlx::FromRow)]
pub struct ExecutionProfileRow {
    pub profile_id: String,
    pub version: String,
    pub name: String,
    pub description: Option<String>,
    pub supported_client_types: String,
    pub agent_kind: String,
    pub system_prompt_template: Option<String>,
    pub turn_prompt_template: Option<String>,
    pub default_session_role: Option<String>,
    pub default_session_description: Option<String>,
    pub handle_prefix: Option<String>,
    pub expected_output_schema: Option<String>,
    pub artifact_contract: String,
    pub default_execution_policy: String,
    pub default_review_policy: String,
    pub metadata: String,
    pub active: bool,
    pub archived_at: Option<String>,
    pub archived_reason: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}
