CREATE TABLE execution_profiles (
    profile_id TEXT NOT NULL,
    version TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    supported_client_types TEXT NOT NULL DEFAULT '[]',
    system_prompt_template TEXT,
    turn_prompt_template TEXT,
    default_session_role TEXT,
    default_session_description TEXT,
    handle_prefix TEXT,
    session_reuse_policy TEXT NOT NULL,
    expected_output_schema TEXT,
    artifact_contract TEXT NOT NULL DEFAULT '{}',
    default_execution_policy TEXT NOT NULL DEFAULT '{}',
    default_review_policy TEXT NOT NULL DEFAULT '{}',
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY(profile_id, version)
);

CREATE INDEX idx_execution_profiles_profile_created ON execution_profiles(profile_id, created_at, version);

INSERT INTO execution_profiles (
    profile_id, version, name, description, supported_client_types,
    system_prompt_template, turn_prompt_template, default_session_role,
    default_session_description, handle_prefix, session_reuse_policy,
    expected_output_schema, artifact_contract, default_execution_policy,
    default_review_policy, metadata
) VALUES
('default', '1', 'Default', 'General coding agent execution template.', '["pi","claude_code","generic"]',
 'You are a coding agent. Follow the assigned task and report concise results.',
 'Execute WorkItem {{work_item_id}}: {{title}}\n\n{{description}}',
 'General coding agent', 'Executes assigned WorkItems.', 'agent', 'reuse_by_workspace_and_profile',
 'free_text', '{}', '{}', '{}', '{"builtin":true}'),
('planner', '1', 'Planner', 'Generates initial WorkItem DAG only.', '["pi","claude_code","generic"]',
 'You are a planning agent. Only produce structured DAG output. Do not modify files.',
 'Plan task {{task_id}} into WorkItems. Input:\n{{input}}',
 'Planner', 'Plans task DAGs.', 'planner', 'fresh_per_run',
 'dag_v1', '{}', '{"allow_file_writes":false}', '{}', '{"builtin":true}'),
('replanner', '1', 'Replanner', 'Generates DAGPatch from signals or replan requests.', '["pi","claude_code","generic"]',
 'You are a replanning agent. Only output DAGPatch JSON. Do not modify files or execute code.',
 'Replan for WorkItem {{work_item_id}} using signal:\n{{signal}}',
 'Replanner', 'Produces DAG patches for tasks.', 'replanner', 'fresh_per_run',
 'dag_patch_v1', '{}', '{"allow_file_writes":false}', '{}', '{"builtin":true}'),
('implementer', '1', 'Implementer', 'Implements assigned WorkItems and runs relevant checks.', '["pi","claude_code","generic"]',
 'You are an implementation agent. Stay within the assigned WorkItem and run relevant checks.',
 'Implement WorkItem {{work_item_id}}: {{title}}\n\n{{description}}',
 'Implementer', 'Implements assigned WorkItems.', 'impl', 'reuse_by_workspace_and_profile',
 'work_item_result_v1', '{"produces":["patch","summary"]}', '{}', '{}', '{"builtin":true}'),
('reviewer', '1', 'Reviewer', 'Reviews WorkItem outputs without modifying files by default.', '["pi","claude_code","generic"]',
 'You are a review agent. Review the supplied output. Do not modify files unless explicitly allowed.',
 'Review WorkItem {{work_item_id}} output:\n{{output}}',
 'Reviewer', 'Reviews WorkItem outputs.', 'reviewer', 'fresh_per_work_item',
 'review_result_v1', '{"produces":["review"]}', '{"allow_file_writes":false}', '{}', '{"builtin":true}'),
('tester', '1', 'Tester', 'Runs verification and produces test reports.', '["pi","claude_code","generic"]',
 'You are a test agent. Run relevant verification and report results. Avoid broad refactors.',
 'Test WorkItem {{work_item_id}}: {{title}}\n\n{{description}}',
 'Tester', 'Verifies assigned WorkItems.', 'tester', 'reuse_by_task_and_profile',
 'test_report_v1', '{"produces":["test_report"]}', '{}', '{}', '{"builtin":true}'),
('debugger', '1', 'Debugger', 'Investigates failures and proposes or applies scoped fixes according to policy.', '["pi","claude_code","generic"]',
 'You are a debugging agent. Identify root cause before fixing. Stay within policy.',
 'Debug WorkItem {{work_item_id}} failure:\n{{failure}}',
 'Debugger', 'Debugs failed WorkItems.', 'debugger', 'reuse_by_task_and_profile',
 'debug_report_v1', '{"produces":["debug_report"]}', '{}', '{}', '{"builtin":true}');
