mod activation_failure;
mod atomic_transition;
mod failure_cleanup;
mod fixture;
mod idle_convergence;
mod lagged_event_reconciliation;
mod patch_interruption;
mod restart_recovery;
mod test_doubles;
